# Generated by Django 5.0.7 on 2024-07-20 08:25

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0002_sectiondetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectiondetail',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
